# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export LANG=en_US.UTF-8

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias 'l=lsd'
alias 'la=lsd -A'
alias 'll=lsd -l'
alias 'lq=lsd -Q'
alias 'lr=lsd -R'
alias 'lrs=lsd -lrS'
alias 'lrt=lsd -lrt'
alias 'lrta=lsd -lrtA'
alias 'lrth=lsd -lrth'
alias 'lrtha=lsd -lrthA'
alias 'j=jobs -l'
alias 'tf=tail -F'
alias 'grep=grep --colour'
alias 'vnice=nice -n 20 ionice -c 3'
alias "tree=tree -A -I 'CVS|*~'"

# Play safe!
alias 'rm=rm -i'
alias 'mv=mv -i'
alias 'cp=cp -i'

# For convenience
alias 'mkdir=mkdir -p'
alias 'dus=du -ms * | sort -n'
alias 'lg=lazygit'

# Put this in your .zshrc or .bashrc file
# Install `tree` first — brew install tree
function t() {
  # Defaults to 3 levels deep, do more with `t 5` or `t 1`
  # pass additional args after
  tree -I '.git|node_modules|bower_components|.DS_Store' --dirsfirst --filelimit 100 -L ${1:-3} -aC $2
}

eval "$(rbenv init -)"
# eval "$(~/.rbenv/bin/rbenv init - zsh)"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.dotfiles/submodules/zsh-nvm-auto-switch/zsh-nvm-auto-switch.plugin.zsh ] && source ~/.dotfiles/submodules/zsh-nvm-auto-switch/zsh-nvm-auto-switch.plugin.zsh
[ -f ~/.dotfiles/zsh/plugins/nnn.zsh ] && source ~/.dotfiles/zsh/plugins/nnn.zsh

# Jump around
eval "$(zoxide init zsh)"

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

# . $(pack completion --shell zsh)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Fixes history search for my setup
# https://github.com/sorin-ionescu/prezto/issues/989#issuecomment-150843824
# bindkey -L | grep '\^R'
bindkey "^R" history-incremental-pattern-search-backward

# pnpm
export PNPM_HOME="/Users/gambo/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# golang
export GOLANG_HOME="/Users/gambo/go"
export PATH="$GOLANG_HOME:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

# php
export PATH="$PATH:/Users/gambo/.composer/vendor/bin"
