#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export LANG=en_US.UTF-8

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias 'l=lsd'
alias 'la=lsd -A'
alias 'll=lsd -l'
alias 'lq=lsd -Q'
alias 'lr=lsd -R'
alias 'lrs=lsd -lrS'
alias 'lrt=lsd -lrt'
alias 'lrta=lsd -lrtA'
alias 'lrth=lsd -lrth'
alias 'lrtha=lsd -lrthA'
alias 'j=jobs -l'
alias 'tf=tail -F'
alias 'z=fasd_cd'
alias 'grep=grep --colour'
alias 'vnice=nice -n 20 ionice -c 3'
alias "tree=tree -A -I 'CVS|*~'"

# Play safe!
alias 'rm=rm -i'
alias 'mv=mv -i'
alias 'cp=cp -i'

# For convenience
alias 'mkdir=mkdir -p'
alias 'dus=du -ms * | sort -n'

# Put this in your .zshrc or .bashrc file
# Install `tree` first — brew install tree
function t() {
  # Defaults to 3 levels deep, do more with `t 5` or `t 1`
  # pass additional args after
  tree -I '.git|node_modules|bower_components|.DS_Store' --dirsfirst --filelimit 100 -L ${1:-3} -aC $2
}

eval "$(rbenv init -)"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

# export PATH="$HOME/.rbenv/bin:$PATH"
# [ -f ~/.rbenv/completions/rbenv.zsh ] && source ~/.rbenv/completions/rbenv.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

# MAGIC_ENTER_OTHER_COMMAND='clear && lsd -lha | lolcat -S 1 -F 0.04'
MAGIC_ENTER_OTHER_COMMAND='clear && lsd -lha'
MAGIC_ENTER_GIT_COMMAND="clear && git status | lolcat -S 1 -F 0.04"
[ -f ~/.dotfiles/zsh/plugins/magic-enter.plugin.zsh ] && source ~/.dotfiles/zsh/plugins/magic-enter.plugin.zsh
source ~/.dotfiles/submodules/zsh-nvm-auto-switch/zsh-nvm-auto-switch.plugin.zsh

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

# . $(pack completion --shell zsh)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
